In [20]:
import pickle
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import tensorflow as tf

In [21]:
with open('X_train_scaled_dic.pickle', 'rb') as f:
    X_train_scaled_dic = pickle.load(f)
with open('X_test_scaled_dic.pickle', 'rb') as f:
    X_test_scaled_dic = pickle.load(f)
with open('y_train_dic.pickle', 'rb') as f:
    y_train_dic= pickle.load(f)
with open('y_test_dic.pickle', 'rb') as f:
    y_test_dic= pickle.load(f)

In [22]:
with open('sector.pickle', 'rb') as f:
    sector = pickle.load(f)

# 윈도우 데이터 셋 생성

In [23]:
# 윈도우 데이터셋 생성 함수
def windowed_dataset(X, y, X_size, y_size, X_shift, y_shift, X_stride, y_stride, batch_size):
    
    # numpy array x(input)를 Dataset으로 변환
    ds_x = tf.data.Dataset.from_tensor_slices(X)
    
    #윈도우셋 구성
    ds_x = ds_x.window(size=X_size,stride=X_stride, shift=X_shift, drop_remainder=True)
    #한 차원 줄야사 반환
    ds_x = ds_x.flat_map(lambda x: x.batch(X_size))
    
    ds_y = tf.data.Dataset.from_tensor_slices(y)
    
    #같은 인덱스에 있는 애들 끼리 묶기
    ds = tf.data.Dataset.zip((ds_x, ds_y))

    
    return ds.batch(batch_size).prefetch(1)

In [24]:
## 파라미터 지정

In [25]:
#윈도우 사이즈
WINDOW_SIZE = 10
# X에 대한 윈도우 함수 설정값
X_size = WINDOW_SIZE
X_shift = 1
X_stride = 1
# y에 대한 윈도우 함수 설정값
y_size = 1
y_shift = 1
y_stride = 1

batch_size = 32

In [26]:
tf_dataset_train_dic={}
for sector_name, sector_df in X_train_scaled_dic.items():
    tf_dataset_train_dic[sector_name] = {}
    for stock_code, df in sector_df.items():
        X_train = df
        y_train = y_train_dic[sector_name][stock_code]
        tf_dataset_train_dic[sector_name][stock_code] = windowed_dataset(X_train,y_train[WINDOW_SIZE:], X_size, y_size,
                                    X_shift, y_shift, X_stride, y_stride, batch_size)

        
        
tf_dataset_test_dic={}
for sector_name, sector_df in X_test_scaled_dic.items():
    tf_dataset_test_dic[sector_name] = {}
    for stock_code, df in sector_df.items():
        X_test = df
        y_test = y_test_dic[sector_name][stock_code]
        tf_dataset_test_dic[sector_name][stock_code] = windowed_dataset(X_test,y_test[WINDOW_SIZE:], X_size, y_size,
                                    X_shift, y_shift, X_stride, y_stride, batch_size)

In [27]:
# 데이터 shape, 미리보기로 체크
for x, y in tf_dataset_train_dic['Food']['097950'].take(1):
    print('X:', x.shape)
    print(x[:3])
    print()
    print('Y:', y.shape)
    print(y[:3])
    print('-'*100)

X: (32, 10, 5)
tf.Tensor(
[[[0.08718198 0.09461967 0.08545455 0.08431373 0.08082707]
  [0.04791903 0.08163265 0.07818182 0.08627451 0.08458647]
  [0.05072111 0.08534323 0.08727273 0.08823529 0.09586466]
  [0.12175059 0.1038961  0.09636364 0.10392157 0.10338346]
  [0.09202992 0.10760668 0.10545455 0.11568627 0.11466165]
  [0.09526414 0.12244898 0.12181818 0.1254902  0.11654135]
  [0.07396998 0.11131725 0.11636364 0.11764706 0.12030075]
  [0.06126101 0.11131725 0.11272727 0.10588235 0.10526316]
  [0.07603778 0.11502783 0.10363636 0.09803922 0.10714286]
  [0.15095811 0.10760668 0.12909091 0.10588235 0.14097744]]

 [[0.04791903 0.08163265 0.07818182 0.08627451 0.08458647]
  [0.05072111 0.08534323 0.08727273 0.08823529 0.09586466]
  [0.12175059 0.1038961  0.09636364 0.10392157 0.10338346]
  [0.09202992 0.10760668 0.10545455 0.11568627 0.11466165]
  [0.09526414 0.12244898 0.12181818 0.1254902  0.11654135]
  [0.07396998 0.11131725 0.11636364 0.11764706 0.12030075]
  [0.06126101 0.11131725 0.1

In [28]:
X_train_scaled_dic['Food']['097950'].iloc[:30]

거래량        시가        고가        저가        종가
일자                                                          
2010-06-22  0.087182  0.094620  0.085455  0.084314  0.080827
2010-06-23  0.047919  0.081633  0.078182  0.086275  0.084586
2010-06-24  0.050721  0.085343  0.087273  0.088235  0.095865
2010-06-25  0.121751  0.103896  0.096364  0.103922  0.103383
2010-06-28  0.092030  0.107607  0.105455  0.115686  0.114662
2010-06-29  0.095264  0.122449  0.121818  0.125490  0.116541
2010-06-30  0.073970  0.111317  0.116364  0.117647  0.120301
2010-07-01  0.061261  0.111317  0.112727  0.105882  0.105263
2010-07-02  0.076038  0.115028  0.103636  0.098039  0.107143
2010-07-05  0.150958  0.107607  0.129091  0.105882  0.140977
2010-07-06  0.389097  0.135436  0.183636  0.143137  0.186090
2010-07-07  0.249067  0.205937  0.205455  0.200000  0.197368
2010-07-08  0.140322  0.200371  0.203636  0.205882  0.214286
2010-07-09  0.095475  0.207792  0.198182  0.201961  0.204887
2010-07-12  0.101915  0.198516  0.190909  0.200000  0.191729
2010-07-13  0.262744  0.192950  0.214545  0.207843  0.219925
2010-07-14  0.084407  0.230056  0.223636  0.227451  0.229323
2010-07-15  0.065385  0.220779  0.218182  0.219608  0.227444
2010-07-16  0.063079  0.217069  0.221818  0.225490  0.219925
2010-07-19  0.028897  0.220779  0.207273  0.213725  0.199248
2010-07-20  0.079758  0.191095  0.192727  0.194118  0.191729
2010-07-21  0.083224  0.192950  0.220000  0.207843  0.231203
2010-07-22  0.180000  0.230056  0.249091  0.239216  0.251880
2010-07-23  0.121779  0.241187  0.240000  0.241176  0.234962
2010-07-26  0.061710  0.231911  0.218182  0.223529  0.208647
2010-07-27  0.078713  0.215213  0.203636  0.207843  0.216165
2010-07-28  0.062976  0.209647  0.212727  0.213725  0.227444
2010-07-29  0.058089  0.217069  0.221818  0.227451  0.234962
2010-07-30  0.573048  0.196660  0.194545  0.156863  0.165414
2010-08-02  0.325263  0.170686  0.158182  0.150980  0.146617

In [29]:
y_train_dic['Food']['097950'].iloc[[10,11,12]]

상향  하향  횡보
일자                    
2010-07-06   0   1   0
2010-07-07   0   1   0
2010-07-08   1   0   0

In [30]:
for sector_name, sector_tf in tf_dataset_train_dic.items():
    for stock_code, tf_dataset in sector_tf.items():
        for data in tf_dataset.take(1):
            print(stock_code)
            print(f'데이터셋(X) 구성(batch_size, window_size, feature갯수): {data[0].shape}')
            print(f'데이터셋(Y) 구성(batch_size, window_size, feature갯수): {data[1].shape}')

097950
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
271560
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
000080
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
004370
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
005300
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
093050
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
020000
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
105630
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
001070
데이터셋(X) 구

036570
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
005380
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
000270
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
012330
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
033780
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)
009150
데이터셋(X) 구성(batch_size, window_size, feature갯수): (32, 10, 5)
데이터셋(Y) 구성(batch_size, window_size, feature갯수): (32, 3)


# 모델

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Conv1D, Lambda
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tqdm import tqdm


In [32]:
model_dic ={}
for sector_name, stock_list in sector.items():
    model_dic[sector_name] = {}
    for stock_code in stock_list:
        model_dic[sector_name][stock_code] = Sequential([
            # 1차원 feature map 생성
            Conv1D(filters=32, kernel_size=5,
                   padding="causal",
                   activation="relu",
                   #feature의 개수 3개
                   input_shape=[WINDOW_SIZE, 5]),
            # LSTM
            LSTM(16, activation='tanh'),
            Dense(16, activation="relu"),
            Dense(3,activation='softmax'),
        ])

In [33]:
optimizer = Adam(0.0005)
for sector_name, sector_model_dic in model_dic.items():
    for model in sector_model_dic.values():
        model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['acc'])

In [34]:
# earlystopping은 10번 epoch통안 val_loss 개선이 없다면 학습을 멈춥니다.
earlystopping = EarlyStopping(monitor='val_loss', patience=10)

In [35]:
filename_dic={}
for sector_name,stock_list in sector.items():
    filename_dic[sector_name] = {}
    for stock_code in stock_list:
        filename_dic[sector_name][stock_code] = os.path.join('MC',sector_name, stock_code+'ckeckpointer.ckpt')
        
        
with open('filename_dic.pickle','wb') as f:
    pickle.dump(filename_dic,f)

In [36]:
filename_dic['Food']

{'097950': 'MC\\Food\\097950ckeckpointer.ckpt',
 '271560': 'MC\\Food\\271560ckeckpointer.ckpt',
 '000080': 'MC\\Food\\000080ckeckpointer.ckpt',
 '004370': 'MC\\Food\\004370ckeckpointer.ckpt',
 '005300': 'MC\\Food\\005300ckeckpointer.ckpt'}

In [37]:
#체크포인트를 저장    
mc_dic = {}
for sector_name, filename_sector_dic in filename_dic.items():
    mc_dic[sector_name] = {}
    for stock_code, filename in filename_sector_dic.items():
        mc_dic[sector_name][stock_code] = ModelCheckpoint(filename, 
                             save_weights_only=True, 
                             save_best_only=True, 
                             monitor='val_acc',
                             verbose=1)

In [38]:
history_dic={}
# 학습+저장
for sector_name, tf_dataset_dic in tf_dataset_train_dic.items():
    history_dic[sector_name] = {}
    for stock_code, train_data in tf_dataset_dic.items():
        mc = mc_dic[sector_name][stock_code]
        test_data = tf_dataset_test_dic[sector_name][stock_code]
        history = model_dic[sector_name][stock_code].fit(train_data, 
                            validation_data=(test_data), 
                            epochs=80, 
                            callbacks=[mc, earlystopping])
        history_dic[sector_name][stock_code] = history

Epoch 1/80
75/75 [==============================] - 6s 33ms/step - loss: 1.0225 - acc: 0.4383 - val_loss: 0.8663 - val_acc: 0.4796

Epoch 00001: val_acc improved from -inf to 0.47959, saving model to MC\Food\097950ckeckpointer.ckpt
Epoch 2/80
75/75 [==============================] - 1s 17ms/step - loss: 0.8266 - acc: 0.5000 - val_loss: 0.7857 - val_acc: 0.4847

Epoch 00002: val_acc improved from 0.47959 to 0.48469, saving model to MC\Food\097950ckeckpointer.ckpt
Epoch 3/80
75/75 [==============================] - 1s 19ms/step - loss: 0.7906 - acc: 0.4895 - val_loss: 0.7812 - val_acc: 0.5102

Epoch 00003: val_acc improved from 0.48469 to 0.51020, saving model to MC\Food\097950ckeckpointer.ckpt
Epoch 4/80
75/75 [==============================] - 1s 17ms/step - loss: 0.7866 - acc: 0.4744 - val_loss: 0.7791 - val_acc: 0.5170

Epoch 00004: val_acc improved from 0.51020 to 0.51701, saving model to MC\Food\097950ckeckpointer.ckpt
Epoch 5/80
75/75 [==============================] - 1s 17ms/ste

75/75 [==============================] - 1s 15ms/step - loss: 0.7795 - acc: 0.5151 - val_loss: 0.7722 - val_acc: 0.5289

Epoch 00044: val_acc did not improve from 0.53061
Epoch 45/80
75/75 [==============================] - 1s 17ms/step - loss: 0.7800 - acc: 0.5147 - val_loss: 0.7699 - val_acc: 0.5289

Epoch 00045: val_acc did not improve from 0.53061
Epoch 46/80
75/75 [==============================] - 1s 17ms/step - loss: 0.7800 - acc: 0.5139 - val_loss: 0.7686 - val_acc: 0.5323

Epoch 00046: val_acc improved from 0.53061 to 0.53231, saving model to MC\Food\097950ckeckpointer.ckpt
Epoch 47/80
75/75 [==============================] - 1s 19ms/step - loss: 0.7791 - acc: 0.5164 - val_loss: 0.7718 - val_acc: 0.5306

Epoch 00047: val_acc did not improve from 0.53231
Epoch 48/80
75/75 [==============================] - 1s 20ms/step - loss: 0.7793 - acc: 0.5176 - val_loss: 0.7753 - val_acc: 0.5272

Epoch 00048: val_acc did not improve from 0.53231
Epoch 49/80
75/75 [=========================

31/31 [==============================] - 1s 21ms/step - loss: 0.8593 - acc: 0.5128 - val_loss: 0.9260 - val_acc: 0.4454

Epoch 00030: val_acc did not improve from 0.47479
Epoch 31/80
31/31 [==============================] - 1s 18ms/step - loss: 0.8591 - acc: 0.5128 - val_loss: 0.9259 - val_acc: 0.4454

Epoch 00031: val_acc did not improve from 0.47479
Epoch 32/80
31/31 [==============================] - 1s 20ms/step - loss: 0.8589 - acc: 0.5138 - val_loss: 0.9259 - val_acc: 0.4454

Epoch 00032: val_acc did not improve from 0.47479
Epoch 33/80
31/31 [==============================] - 1s 18ms/step - loss: 0.8588 - acc: 0.5138 - val_loss: 0.9259 - val_acc: 0.4454

Epoch 00033: val_acc did not improve from 0.47479
Epoch 34/80
31/31 [==============================] - 1s 19ms/step - loss: 0.8586 - acc: 0.5148 - val_loss: 0.9259 - val_acc: 0.4454

Epoch 00034: val_acc did not improve from 0.47479
Epoch 35/80
31/31 [==============================] - 1s 21ms/step - loss: 0.8585 - acc: 0.5158 - 


Epoch 00017: val_acc did not improve from 0.42687
Epoch 18/80
75/75 [==============================] - 1s 17ms/step - loss: 1.0742 - acc: 0.4123 - val_loss: 1.0504 - val_acc: 0.4269

Epoch 00018: val_acc did not improve from 0.42687
Epoch 19/80
75/75 [==============================] - 1s 17ms/step - loss: 1.0741 - acc: 0.4123 - val_loss: 1.0505 - val_acc: 0.4269

Epoch 00019: val_acc did not improve from 0.42687
Epoch 1/80
75/75 [==============================] - 8s 39ms/step - loss: 0.8451 - acc: 0.4828 - val_loss: 0.7678 - val_acc: 0.5289

Epoch 00001: val_acc improved from -inf to 0.52891, saving model to MC\Food\004370ckeckpointer.ckpt
Epoch 2/80
75/75 [==============================] - 1s 18ms/step - loss: 0.8125 - acc: 0.5042 - val_loss: 0.7620 - val_acc: 0.5289

Epoch 00002: val_acc did not improve from 0.52891
Epoch 3/80
75/75 [==============================] - 2s 22ms/step - loss: 0.8141 - acc: 0.5160 - val_loss: 0.7573 - val_acc: 0.5476s - loss: 0.8120 - acc: 0.51

Epoch 000

75/75 [==============================] - 1s 20ms/step - loss: 1.0685 - acc: 0.3959 - val_loss: 1.1657 - val_acc: 0.2568A: 0s - loss: 1.0682 - acc:

Epoch 00010: val_acc did not improve from 0.33673
Epoch 11/80
75/75 [==============================] - 1s 19ms/step - loss: 1.0676 - acc: 0.4013 - val_loss: 1.1921 - val_acc: 0.2483

Epoch 00011: val_acc did not improve from 0.33673
Epoch 1/80
75/75 [==============================] - 7s 37ms/step - loss: 1.0625 - acc: 0.4043 - val_loss: 1.0299 - val_acc: 0.4405

Epoch 00001: val_acc improved from -inf to 0.44048, saving model to MC\Clothing\020000ckeckpointer.ckpt
Epoch 2/80
75/75 [==============================] - 1s 15ms/step - loss: 1.0515 - acc: 0.4437 - val_loss: 1.0224 - val_acc: 0.4609

Epoch 00002: val_acc improved from 0.44048 to 0.46088, saving model to MC\Clothing\020000ckeckpointer.ckpt
Epoch 3/80
75/75 [==============================] - 1s 18ms/step - loss: 1.0471 - acc: 0.4446 - val_loss: 1.0184 - val_acc: 0.4949

Epoch 00003:


Epoch 00006: val_acc did not improve from 0.42177
Epoch 7/80
75/75 [==============================] - 1s 14ms/step - loss: 0.8122 - acc: 0.6381 - val_loss: 1.0798 - val_acc: 0.4218

Epoch 00007: val_acc did not improve from 0.42177
Epoch 8/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8053 - acc: 0.6381 - val_loss: 1.0800 - val_acc: 0.4218

Epoch 00008: val_acc did not improve from 0.42177
Epoch 9/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8010 - acc: 0.6381 - val_loss: 1.0813 - val_acc: 0.4218

Epoch 00009: val_acc did not improve from 0.42177
Epoch 10/80
75/75 [==============================] - 1s 14ms/step - loss: 0.7979 - acc: 0.6381 - val_loss: 1.0819 - val_acc: 0.4218

Epoch 00010: val_acc did not improve from 0.42177
Epoch 11/80
75/75 [==============================] - 1s 15ms/step - loss: 0.7956 - acc: 0.6381 - val_loss: 1.0829 - val_acc: 0.4218

Epoch 00011: val_acc did not improve from 0.42177
Epoch 12/80
75/75 [==================

Epoch 26/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8396 - acc: 0.4916 - val_loss: 0.7932 - val_acc: 0.5459

Epoch 00026: val_acc did not improve from 0.56633
Epoch 27/80
75/75 [==============================] - 1s 14ms/step - loss: 0.8396 - acc: 0.4924 - val_loss: 0.7932 - val_acc: 0.5459

Epoch 00027: val_acc did not improve from 0.56633
Epoch 28/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8394 - acc: 0.4916 - val_loss: 0.7933 - val_acc: 0.5425

Epoch 00028: val_acc did not improve from 0.56633
Epoch 29/80
75/75 [==============================] - 1s 14ms/step - loss: 0.8395 - acc: 0.4920 - val_loss: 0.7930 - val_acc: 0.5442

Epoch 00029: val_acc did not improve from 0.56633
Epoch 30/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8394 - acc: 0.4916 - val_loss: 0.7930 - val_acc: 0.5442

Epoch 00030: val_acc did not improve from 0.56633
Epoch 31/80
75/75 [==============================] - 1s 14ms/step - loss: 0.8393 - ac

75/75 [==============================] - 1s 15ms/step - loss: 0.8374 - acc: 0.4929 - val_loss: 0.7913 - val_acc: 0.5408

Epoch 00071: val_acc did not improve from 0.56633
Epoch 72/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8373 - acc: 0.4929 - val_loss: 0.7917 - val_acc: 0.5408

Epoch 00072: val_acc did not improve from 0.56633
Epoch 73/80
75/75 [==============================] - 1s 14ms/step - loss: 0.8372 - acc: 0.4945 - val_loss: 0.7921 - val_acc: 0.5425

Epoch 00073: val_acc did not improve from 0.56633
Epoch 74/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8370 - acc: 0.4950 - val_loss: 0.7927 - val_acc: 0.5408

Epoch 00074: val_acc did not improve from 0.56633
Epoch 75/80
75/75 [==============================] - 1s 18ms/step - loss: 0.8371 - acc: 0.4937 - val_loss: 0.7904 - val_acc: 0.5425

Epoch 00075: val_acc did not improve from 0.56633
Epoch 76/80
75/75 [==============================] - 2s 22ms/step - loss: 0.8374 - acc: 0.4895 - 

75/75 [==============================] - 1s 17ms/step - loss: 0.8391 - acc: 0.4916 - val_loss: 0.7901 - val_acc: 0.5408

Epoch 00009: val_acc did not improve from 0.55102
Epoch 10/80
75/75 [==============================] - 1s 14ms/step - loss: 0.8388 - acc: 0.4903 - val_loss: 0.7902 - val_acc: 0.5408

Epoch 00010: val_acc did not improve from 0.55102
Epoch 11/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8385 - acc: 0.4933 - val_loss: 0.7901 - val_acc: 0.5408

Epoch 00011: val_acc did not improve from 0.55102
Epoch 12/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8384 - acc: 0.4941 - val_loss: 0.7902 - val_acc: 0.5408

Epoch 00012: val_acc did not improve from 0.55102
Epoch 1/80
35/35 [==============================] - 6s 55ms/step - loss: 0.9186 - acc: 0.4626 - val_loss: 0.7765 - val_acc: 0.5185

Epoch 00001: val_acc improved from -inf to 0.51852, saving model to MC\Medicine\207940ckeckpointer.ckpt
Epoch 2/80
35/35 [==========================

75/75 [==============================] - 1s 15ms/step - loss: 0.9024 - acc: 0.4937 - val_loss: 0.7570 - val_acc: 0.4796

Epoch 00028: val_acc did not improve from 0.47959
Epoch 29/80
75/75 [==============================] - 1s 16ms/step - loss: 0.9021 - acc: 0.4916 - val_loss: 0.7571 - val_acc: 0.4796

Epoch 00029: val_acc did not improve from 0.47959
Epoch 30/80
75/75 [==============================] - 1s 16ms/step - loss: 0.9017 - acc: 0.4916 - val_loss: 0.7570 - val_acc: 0.4796

Epoch 00030: val_acc did not improve from 0.47959
Epoch 31/80
75/75 [==============================] - 1s 17ms/step - loss: 0.9014 - acc: 0.4908 - val_loss: 0.7569 - val_acc: 0.4796

Epoch 00031: val_acc did not improve from 0.47959
Epoch 32/80
75/75 [==============================] - 1s 17ms/step - loss: 0.9011 - acc: 0.4962 - val_loss: 0.7569 - val_acc: 0.4796

Epoch 00032: val_acc did not improve from 0.47959
Epoch 33/80
75/75 [==============================] - 1s 18ms/step - loss: 0.9008 - acc: 0.4958 - 

75/75 [==============================] - 1s 15ms/step - loss: 1.0873 - acc: 0.4614 - val_loss: 1.1008 - val_acc: 0.4439

Epoch 00003: val_acc did not improve from 0.44388
Epoch 4/80
75/75 [==============================] - 1s 14ms/step - loss: 1.0761 - acc: 0.4614 - val_loss: 1.0880 - val_acc: 0.4439

Epoch 00004: val_acc did not improve from 0.44388
Epoch 5/80
75/75 [==============================] - 1s 14ms/step - loss: 1.0619 - acc: 0.4719 - val_loss: 1.0347 - val_acc: 0.4439

Epoch 00005: val_acc did not improve from 0.44388
Epoch 6/80
75/75 [==============================] - 1s 15ms/step - loss: 1.0397 - acc: 0.4752 - val_loss: 0.9669 - val_acc: 0.4439

Epoch 00006: val_acc did not improve from 0.44388
Epoch 7/80
75/75 [==============================] - 1s 12ms/step - loss: 1.0234 - acc: 0.4777 - val_loss: 0.9025 - val_acc: 0.4439

Epoch 00007: val_acc did not improve from 0.44388
Epoch 8/80
75/75 [==============================] - 1s 12ms/step - loss: 1.0122 - acc: 0.4861 - val_l


Epoch 00013: val_acc did not improve from 0.50170
Epoch 14/80
75/75 [==============================] - 1s 12ms/step - loss: 1.0140 - acc: 0.4513 - val_loss: 0.9667 - val_acc: 0.4949

Epoch 00014: val_acc did not improve from 0.50170
Epoch 15/80
75/75 [==============================] - 1s 12ms/step - loss: 1.0116 - acc: 0.4475 - val_loss: 0.9664 - val_acc: 0.5000

Epoch 00015: val_acc did not improve from 0.50170
Epoch 16/80
75/75 [==============================] - 1s 15ms/step - loss: 1.0119 - acc: 0.4521 - val_loss: 0.9663 - val_acc: 0.5000

Epoch 00016: val_acc did not improve from 0.50170
Epoch 17/80
75/75 [==============================] - 1s 14ms/step - loss: 1.0113 - acc: 0.4517 - val_loss: 0.9661 - val_acc: 0.5000

Epoch 00017: val_acc did not improve from 0.50170
Epoch 18/80
75/75 [==============================] - 1s 11ms/step - loss: 1.0112 - acc: 0.4547 - val_loss: 0.9661 - val_acc: 0.5000

Epoch 00018: val_acc did not improve from 0.50170
Epoch 19/80
75/75 [===============

75/75 [==============================] - 1s 15ms/step - loss: 1.0064 - acc: 0.4542 - val_loss: 0.9645 - val_acc: 0.5000

Epoch 00058: val_acc did not improve from 0.50340
Epoch 59/80
75/75 [==============================] - 1s 14ms/step - loss: 1.0064 - acc: 0.4542 - val_loss: 0.9645 - val_acc: 0.5000

Epoch 00059: val_acc did not improve from 0.50340
Epoch 60/80
75/75 [==============================] - 1s 16ms/step - loss: 1.0063 - acc: 0.4542 - val_loss: 0.9645 - val_acc: 0.5017

Epoch 00060: val_acc did not improve from 0.50340
Epoch 61/80
75/75 [==============================] - 1s 15ms/step - loss: 1.0063 - acc: 0.4622 - val_loss: 0.9639 - val_acc: 0.5000

Epoch 00061: val_acc did not improve from 0.50340
Epoch 62/80
75/75 [==============================] - 1s 16ms/step - loss: 1.0060 - acc: 0.4538 - val_loss: 0.9645 - val_acc: 0.5017

Epoch 00062: val_acc did not improve from 0.50340
Epoch 63/80
75/75 [==============================] - 1s 14ms/step - loss: 1.0059 - acc: 0.4526 - 

75/75 [==============================] - 1s 14ms/step - loss: 0.7833 - acc: 0.5176 - val_loss: 0.7725 - val_acc: 0.5306

Epoch 00022: val_acc did not improve from 0.55782
Epoch 23/80
75/75 [==============================] - 1s 16ms/step - loss: 0.7832 - acc: 0.5181 - val_loss: 0.7726 - val_acc: 0.5272

Epoch 00023: val_acc did not improve from 0.55782
Epoch 24/80
75/75 [==============================] - 1s 14ms/step - loss: 0.7831 - acc: 0.5151 - val_loss: 0.7728 - val_acc: 0.5221

Epoch 00024: val_acc did not improve from 0.55782
Epoch 25/80
75/75 [==============================] - 1s 14ms/step - loss: 0.7830 - acc: 0.5160 - val_loss: 0.7728 - val_acc: 0.5221

Epoch 00025: val_acc did not improve from 0.55782
Epoch 1/80
75/75 [==============================] - 6s 33ms/step - loss: 0.8167 - acc: 0.5021 - val_loss: 0.8061 - val_acc: 0.4388

Epoch 00001: val_acc improved from -inf to 0.43878, saving model to MC\Metal\010130ckeckpointer.ckpt
Epoch 2/80
75/75 [=============================

75/75 [==============================] - 1s 17ms/step - loss: 0.8933 - acc: 0.5243 - val_loss: 1.4419 - val_acc: 0.3486

Epoch 00006: val_acc did not improve from 0.34864
Epoch 7/80
75/75 [==============================] - 1s 18ms/step - loss: 0.8924 - acc: 0.5252 - val_loss: 1.4704 - val_acc: 0.3486

Epoch 00007: val_acc did not improve from 0.34864
Epoch 8/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8908 - acc: 0.5407 - val_loss: 1.5011 - val_acc: 0.3469

Epoch 00008: val_acc did not improve from 0.34864
Epoch 9/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8897 - acc: 0.5411 - val_loss: 1.5318 - val_acc: 0.3469

Epoch 00009: val_acc did not improve from 0.34864
Epoch 10/80
75/75 [==============================] - 1s 17ms/step - loss: 0.8886 - acc: 0.5403 - val_loss: 1.5681 - val_acc: 0.3469

Epoch 00010: val_acc did not improve from 0.34864
Epoch 11/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8876 - acc: 0.5403 - val

75/75 [==============================] - 2s 21ms/step - loss: 0.8757 - acc: 0.6297 - val_loss: 1.0621 - val_acc: 0.4405

Epoch 00011: val_acc did not improve from 0.44048
Epoch 12/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8754 - acc: 0.6297 - val_loss: 1.0620 - val_acc: 0.4405

Epoch 00012: val_acc did not improve from 0.44048
Epoch 13/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8751 - acc: 0.6297 - val_loss: 1.0618 - val_acc: 0.4405

Epoch 00013: val_acc did not improve from 0.44048
Epoch 14/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8749 - acc: 0.6297 - val_loss: 1.0617 - val_acc: 0.4405

Epoch 00014: val_acc did not improve from 0.44048
Epoch 15/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8747 - acc: 0.6297 - val_loss: 1.0616 - val_acc: 0.4405

Epoch 00015: val_acc did not improve from 0.44048
Epoch 16/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8745 - acc: 0.6297 - 

75/75 [==============================] - 1s 11ms/step - loss: 0.8715 - acc: 0.6297 - val_loss: 1.0605 - val_acc: 0.4405

Epoch 00055: val_acc did not improve from 0.44048
Epoch 1/80
35/35 [==============================] - 5s 44ms/step - loss: 1.0700 - acc: 0.3659 - val_loss: 1.0008 - val_acc: 0.5911

Epoch 00001: val_acc improved from -inf to 0.59108, saving model to MC\Machine\241560ckeckpointer.ckpt
Epoch 2/80
35/35 [==============================] - ETA: 0s - loss: 1.0616 - acc: 0.413 - 1s 17ms/step - loss: 1.0562 - acc: 0.4058 - val_loss: 0.9943 - val_acc: 0.5428

Epoch 00002: val_acc did not improve from 0.59108
Epoch 3/80
35/35 [==============================] - 1s 17ms/step - loss: 1.0529 - acc: 0.4185 - val_loss: 0.9924 - val_acc: 0.5353

Epoch 00003: val_acc did not improve from 0.59108
Epoch 4/80
35/35 [==============================] - 1s 18ms/step - loss: 1.0532 - acc: 0.4112 - val_loss: 0.9867 - val_acc: 0.5502

Epoch 00004: val_acc did not improve from 0.59108
Epoch 5/80

35/35 [==============================] - 0s 14ms/step - loss: 1.0398 - acc: 0.4411 - val_loss: 0.9727 - val_acc: 0.5502

Epoch 00044: val_acc did not improve from 0.59108
Epoch 45/80
35/35 [==============================] - 1s 15ms/step - loss: 1.0398 - acc: 0.4402 - val_loss: 0.9734 - val_acc: 0.5502

Epoch 00045: val_acc did not improve from 0.59108
Epoch 46/80
35/35 [==============================] - 0s 13ms/step - loss: 1.0395 - acc: 0.4420 - val_loss: 0.9725 - val_acc: 0.5502

Epoch 00046: val_acc did not improve from 0.59108
Epoch 47/80
35/35 [==============================] - 0s 14ms/step - loss: 1.0394 - acc: 0.4393 - val_loss: 0.9724 - val_acc: 0.5502

Epoch 00047: val_acc did not improve from 0.59108
Epoch 48/80
35/35 [==============================] - 0s 14ms/step - loss: 1.0393 - acc: 0.4420 - val_loss: 0.9722 - val_acc: 0.5502

Epoch 00048: val_acc did not improve from 0.59108
Epoch 49/80
35/35 [==============================] - 0s 14ms/step - loss: 1.0391 - acc: 0.4420 - 

47/47 [==============================] - 1s 17ms/step - loss: 1.0577 - acc: 0.4023 - val_loss: 0.8887 - val_acc: 0.4235

Epoch 00008: val_acc did not improve from 0.53005
Epoch 9/80
47/47 [==============================] - 1s 17ms/step - loss: 1.0565 - acc: 0.4063 - val_loss: 0.8896 - val_acc: 0.4235

Epoch 00009: val_acc did not improve from 0.53005
Epoch 10/80
47/47 [==============================] - 1s 16ms/step - loss: 1.0555 - acc: 0.4116 - val_loss: 0.8889 - val_acc: 0.4235

Epoch 00010: val_acc did not improve from 0.53005
Epoch 11/80
47/47 [==============================] - 1s 17ms/step - loss: 1.0543 - acc: 0.4190 - val_loss: 0.8906 - val_acc: 0.4235

Epoch 00011: val_acc did not improve from 0.53005
Epoch 12/80
47/47 [==============================] - 1s 18ms/step - loss: 1.0533 - acc: 0.4270 - val_loss: 0.8903 - val_acc: 0.4235

Epoch 00012: val_acc did not improve from 0.53005
Epoch 13/80
47/47 [==============================] - 1s 16ms/step - loss: 1.0529 - acc: 0.4270 - v

75/75 [==============================] - 1s 16ms/step - loss: 0.8399 - acc: 0.4664 - val_loss: 0.7531 - val_acc: 0.4609

Epoch 00011: val_acc did not improve from 0.56803
Epoch 1/80
75/75 [==============================] - 7s 35ms/step - loss: 0.9970 - acc: 0.4295 - val_loss: 0.8720 - val_acc: 0.5289

Epoch 00001: val_acc improved from -inf to 0.52891, saving model to MC\Electronic\066570ckeckpointer.ckpt
Epoch 2/80
75/75 [==============================] - 1s 14ms/step - loss: 0.9439 - acc: 0.4689 - val_loss: 0.8684 - val_acc: 0.5238

Epoch 00002: val_acc did not improve from 0.52891
Epoch 3/80
75/75 [==============================] - 1s 18ms/step - loss: 0.9426 - acc: 0.4757 - val_loss: 0.8684 - val_acc: 0.5204

Epoch 00003: val_acc did not improve from 0.52891
Epoch 4/80
75/75 [==============================] - 1s 18ms/step - loss: 0.9419 - acc: 0.4786 - val_loss: 0.8690 - val_acc: 0.5068

Epoch 00004: val_acc did not improve from 0.52891
Epoch 5/80
75/75 [===========================

75/75 [==============================] - 1s 14ms/step - loss: 0.9468 - acc: 0.4685 - val_loss: 0.9869 - val_acc: 0.4898

Epoch 00027: val_acc did not improve from 0.51701
Epoch 28/80
75/75 [==============================] - 2s 23ms/step - loss: 0.9468 - acc: 0.4673 - val_loss: 0.9865 - val_acc: 0.4898

Epoch 00028: val_acc did not improve from 0.51701
Epoch 29/80
75/75 [==============================] - 1s 17ms/step - loss: 0.9467 - acc: 0.4656 - val_loss: 0.9862 - val_acc: 0.4898

Epoch 00029: val_acc did not improve from 0.51701
Epoch 30/80
75/75 [==============================] - 1s 15ms/step - loss: 0.9467 - acc: 0.4647 - val_loss: 0.9858 - val_acc: 0.4898

Epoch 00030: val_acc did not improve from 0.51701
Epoch 31/80
75/75 [==============================] - 1s 16ms/step - loss: 0.9466 - acc: 0.4635 - val_loss: 0.9853 - val_acc: 0.4898

Epoch 00031: val_acc did not improve from 0.51701
Epoch 32/80
75/75 [==============================] - 1s 19ms/step - loss: 0.9465 - acc: 0.4614 - 

75/75 [==============================] - 1s 19ms/step - loss: 0.9444 - acc: 0.4748 - val_loss: 0.9762 - val_acc: 0.4932

Epoch 00071: val_acc did not improve from 0.51701
Epoch 72/80
75/75 [==============================] - 1s 18ms/step - loss: 0.9444 - acc: 0.4736 - val_loss: 0.9810 - val_acc: 0.4898

Epoch 00072: val_acc did not improve from 0.51701
Epoch 73/80
75/75 [==============================] - 1s 16ms/step - loss: 0.9443 - acc: 0.4744 - val_loss: 0.9770 - val_acc: 0.4915

Epoch 00073: val_acc did not improve from 0.51701
Epoch 74/80
75/75 [==============================] - 1s 16ms/step - loss: 0.9439 - acc: 0.4740 - val_loss: 0.9812 - val_acc: 0.4898

Epoch 00074: val_acc did not improve from 0.51701
Epoch 75/80
75/75 [==============================] - 1s 15ms/step - loss: 0.9441 - acc: 0.4761 - val_loss: 0.9773 - val_acc: 0.4915

Epoch 00075: val_acc did not improve from 0.51701
Epoch 76/80
75/75 [==============================] - 1s 19ms/step - loss: 0.9439 - acc: 0.4715 - 

75/75 [==============================] - 1s 14ms/step - loss: 0.9620 - acc: 0.4689 - val_loss: 1.0050 - val_acc: 0.4626

Epoch 00033: val_acc did not improve from 0.49490
Epoch 34/80
75/75 [==============================] - 1s 14ms/step - loss: 0.9619 - acc: 0.4698 - val_loss: 1.0050 - val_acc: 0.4575

Epoch 00034: val_acc did not improve from 0.49490
Epoch 35/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9618 - acc: 0.4698 - val_loss: 1.0051 - val_acc: 0.4575

Epoch 00035: val_acc did not improve from 0.49490
Epoch 36/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9616 - acc: 0.4698 - val_loss: 1.0051 - val_acc: 0.4575

Epoch 00036: val_acc did not improve from 0.49490
Epoch 37/80
75/75 [==============================] - 1s 14ms/step - loss: 0.9616 - acc: 0.4689 - val_loss: 1.0052 - val_acc: 0.4592

Epoch 00037: val_acc did not improve from 0.49490
Epoch 38/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9615 - acc: 0.4694 - 

75/75 [==============================] - 1s 16ms/step - loss: 0.9726 - acc: 0.4135 - val_loss: 1.0814 - val_acc: 0.3997

Epoch 00011: val_acc did not improve from 0.43707
Epoch 12/80
75/75 [==============================] - 1s 16ms/step - loss: 0.9723 - acc: 0.4152 - val_loss: 1.0822 - val_acc: 0.3997

Epoch 00012: val_acc did not improve from 0.43707
Epoch 13/80
75/75 [==============================] - 1s 16ms/step - loss: 0.9722 - acc: 0.4190 - val_loss: 1.0828 - val_acc: 0.4014

Epoch 00013: val_acc did not improve from 0.43707
Epoch 1/80
75/75 [==============================] - 7s 34ms/step - loss: 1.0523 - acc: 0.3531 - val_loss: 1.1203 - val_acc: 0.2381

Epoch 00001: val_acc improved from -inf to 0.23810, saving model to MC\Transport\011200ckeckpointer.ckpt
Epoch 2/80
75/75 [==============================] - 1s 16ms/step - loss: 0.9164 - acc: 0.6075 - val_loss: 1.1920 - val_acc: 0.4048

Epoch 00002: val_acc improved from 0.23810 to 0.40476, saving model to MC\Transport\011200ckec


Epoch 00015: val_acc did not improve from 0.52551
Epoch 16/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8142 - acc: 0.5000 - val_loss: 0.8011 - val_acc: 0.5204

Epoch 00016: val_acc did not improve from 0.52551
Epoch 17/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8140 - acc: 0.5042 - val_loss: 0.8010 - val_acc: 0.5204

Epoch 00017: val_acc did not improve from 0.52551
Epoch 18/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8139 - acc: 0.5046 - val_loss: 0.8009 - val_acc: 0.5204

Epoch 00018: val_acc did not improve from 0.52551
Epoch 19/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8138 - acc: 0.5038 - val_loss: 0.8007 - val_acc: 0.5204

Epoch 00019: val_acc did not improve from 0.52551
Epoch 20/80
75/75 [==============================] - 1s 19ms/step - loss: 0.8136 - acc: 0.5080 - val_loss: 0.8006 - val_acc: 0.5204

Epoch 00020: val_acc did not improve from 0.52551
Epoch 21/80
75/75 [===============

47/47 [==============================] - 1s 25ms/step - loss: 0.8679 - acc: 0.5081 - val_loss: 0.8790 - val_acc: 0.4986

Epoch 00003: val_acc did not improve from 0.49862
Epoch 4/80
47/47 [==============================] - 1s 26ms/step - loss: 0.8668 - acc: 0.5094 - val_loss: 0.8787 - val_acc: 0.4986

Epoch 00004: val_acc did not improve from 0.49862
Epoch 5/80
47/47 [==============================] - 1s 21ms/step - loss: 0.8671 - acc: 0.5189 - val_loss: 0.8783 - val_acc: 0.4986

Epoch 00005: val_acc did not improve from 0.49862
Epoch 6/80
47/47 [==============================] - 1s 21ms/step - loss: 0.8659 - acc: 0.5243 - val_loss: 0.8774 - val_acc: 0.4986

Epoch 00006: val_acc did not improve from 0.49862
Epoch 7/80
47/47 [==============================] - 1s 17ms/step - loss: 0.8650 - acc: 0.5256 - val_loss: 0.8764 - val_acc: 0.4986

Epoch 00007: val_acc did not improve from 0.49862
Epoch 8/80
47/47 [==============================] - 1s 19ms/step - loss: 0.8645 - acc: 0.5135 - val_l


Epoch 00045: val_acc did not improve from 0.56198
Epoch 46/80
47/47 [==============================] - 1s 17ms/step - loss: 0.8607 - acc: 0.5128 - val_loss: 0.8733 - val_acc: 0.5565

Epoch 00046: val_acc did not improve from 0.56198
Epoch 47/80
47/47 [==============================] - 1s 18ms/step - loss: 0.8607 - acc: 0.5121 - val_loss: 0.8733 - val_acc: 0.5537

Epoch 00047: val_acc did not improve from 0.56198
Epoch 48/80
47/47 [==============================] - 1s 19ms/step - loss: 0.8607 - acc: 0.5121 - val_loss: 0.8733 - val_acc: 0.5537

Epoch 00048: val_acc did not improve from 0.56198
Epoch 49/80
47/47 [==============================] - 1s 17ms/step - loss: 0.8607 - acc: 0.5128 - val_loss: 0.8733 - val_acc: 0.5592

Epoch 00049: val_acc did not improve from 0.56198
Epoch 50/80
47/47 [==============================] - 1s 17ms/step - loss: 0.8606 - acc: 0.5142 - val_loss: 0.8733 - val_acc: 0.5592

Epoch 00050: val_acc did not improve from 0.56198
Epoch 51/80
47/47 [===============


Epoch 00017: val_acc did not improve from 0.46939
Epoch 18/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8053 - acc: 0.5248 - val_loss: 0.9133 - val_acc: 0.4694

Epoch 00018: val_acc did not improve from 0.46939
Epoch 19/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8052 - acc: 0.5248 - val_loss: 0.9136 - val_acc: 0.4694

Epoch 00019: val_acc did not improve from 0.46939
Epoch 20/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8052 - acc: 0.5248 - val_loss: 0.9139 - val_acc: 0.4694

Epoch 00020: val_acc did not improve from 0.46939
Epoch 21/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8051 - acc: 0.5248 - val_loss: 0.9142 - val_acc: 0.4694

Epoch 00021: val_acc did not improve from 0.46939
Epoch 1/80
29/29 [==============================] - 6s 69ms/step - loss: 0.8926 - acc: 0.4861 - val_loss: 0.9332 - val_acc: 0.4885

Epoch 00001: val_acc improved from -inf to 0.48848, saving model to MC\Distribution\2


Epoch 00039: val_acc improved from 0.52074 to 0.52535, saving model to MC\Distribution\282330ckeckpointer.ckpt
Epoch 40/80
29/29 [==============================] - 1s 17ms/step - loss: 0.7967 - acc: 0.5095 - val_loss: 0.8911 - val_acc: 0.5253

Epoch 00040: val_acc did not improve from 0.52535
Epoch 41/80
29/29 [==============================] - 1s 22ms/step - loss: 0.7966 - acc: 0.5095 - val_loss: 0.8910 - val_acc: 0.5253

Epoch 00041: val_acc did not improve from 0.52535
Epoch 42/80
29/29 [==============================] - 1s 20ms/step - loss: 0.7966 - acc: 0.5095 - val_loss: 0.8911 - val_acc: 0.5253

Epoch 00042: val_acc did not improve from 0.52535
Epoch 43/80
29/29 [==============================] - 0s 16ms/step - loss: 0.7966 - acc: 0.5095 - val_loss: 0.8910 - val_acc: 0.5300

Epoch 00043: val_acc improved from 0.52535 to 0.52995, saving model to MC\Distribution\282330ckeckpointer.ckpt
Epoch 44/80
29/29 [==============================] - 1s 19ms/step - loss: 0.7965 - acc: 0.5106 

69/69 [==============================] - 1s 20ms/step - loss: 0.8405 - acc: 0.4862 - val_loss: 0.8847 - val_acc: 0.5074

Epoch 00002: val_acc did not improve from 0.50743
Epoch 3/80
69/69 [==============================] - 1s 20ms/step - loss: 0.8318 - acc: 0.5009 - val_loss: 0.8810 - val_acc: 0.5074

Epoch 00003: val_acc did not improve from 0.50743
Epoch 4/80
69/69 [==============================] - 1s 18ms/step - loss: 0.8306 - acc: 0.5165 - val_loss: 0.8801 - val_acc: 0.5074

Epoch 00004: val_acc did not improve from 0.50743
Epoch 5/80
69/69 [==============================] - 1s 19ms/step - loss: 0.8299 - acc: 0.5225 - val_loss: 0.8799 - val_acc: 0.5074

Epoch 00005: val_acc did not improve from 0.50743
Epoch 6/80
69/69 [==============================] - 1s 18ms/step - loss: 0.8294 - acc: 0.5225 - val_loss: 0.8799 - val_acc: 0.5074

Epoch 00006: val_acc did not improve from 0.50743
Epoch 7/80
69/69 [==============================] - 1s 17ms/step - loss: 0.8290 - acc: 0.5225 - val_l

75/75 [==============================] - 2s 21ms/step - loss: 0.8239 - acc: 0.5231 - val_loss: 0.8352 - val_acc: 0.5153

Epoch 00030: val_acc did not improve from 0.53741
Epoch 31/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8239 - acc: 0.5206 - val_loss: 0.8351 - val_acc: 0.5204

Epoch 00031: val_acc did not improve from 0.53741
Epoch 32/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8238 - acc: 0.5206 - val_loss: 0.8351 - val_acc: 0.5153

Epoch 00032: val_acc did not improve from 0.53741
Epoch 33/80
75/75 [==============================] - 1s 17ms/step - loss: 0.8238 - acc: 0.5214 - val_loss: 0.8350 - val_acc: 0.5204

Epoch 00033: val_acc did not improve from 0.53741
Epoch 34/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8238 - acc: 0.5223 - val_loss: 0.8350 - val_acc: 0.5204

Epoch 00034: val_acc did not improve from 0.53741
Epoch 35/80
75/75 [==============================] - 1s 15ms/step - loss: 0.8237 - acc: 0.5218 - 

75/75 [==============================] - 1s 17ms/step - loss: 0.8225 - acc: 0.5181 - val_loss: 0.8346 - val_acc: 0.5323

Epoch 00075: val_acc did not improve from 0.53741
Epoch 76/80
75/75 [==============================] - 1s 19ms/step - loss: 0.8224 - acc: 0.5193 - val_loss: 0.8345 - val_acc: 0.5323

Epoch 00076: val_acc did not improve from 0.53741
Epoch 77/80
75/75 [==============================] - 1s 16ms/step - loss: 0.8224 - acc: 0.5172 - val_loss: 0.8346 - val_acc: 0.5323

Epoch 00077: val_acc did not improve from 0.53741
Epoch 78/80
75/75 [==============================] - 1s 18ms/step - loss: 0.8224 - acc: 0.5189 - val_loss: 0.8346 - val_acc: 0.5323

Epoch 00078: val_acc did not improve from 0.53741
Epoch 79/80
75/75 [==============================] - 1s 17ms/step - loss: 0.8223 - acc: 0.5202 - val_loss: 0.8346 - val_acc: 0.5323

Epoch 00079: val_acc did not improve from 0.53741
Epoch 80/80
75/75 [==============================] - 1s 17ms/step - loss: 0.8223 - acc: 0.5181 - 


Epoch 00005: val_acc did not improve from 0.43197
Epoch 6/80
75/75 [==============================] - 2s 24ms/step - loss: 1.0022 - acc: 0.4597 - val_loss: 0.9300 - val_acc: 0.4099

Epoch 00006: val_acc did not improve from 0.43197
Epoch 7/80
75/75 [==============================] - 2s 20ms/step - loss: 1.0003 - acc: 0.4492 - val_loss: 0.9298 - val_acc: 0.4065

Epoch 00007: val_acc did not improve from 0.43197
Epoch 8/80
75/75 [==============================] - 1s 17ms/step - loss: 0.9999 - acc: 0.4635 - val_loss: 0.9298 - val_acc: 0.4065

Epoch 00008: val_acc did not improve from 0.43197
Epoch 9/80
75/75 [==============================] - 1s 17ms/step - loss: 0.9991 - acc: 0.4647 - val_loss: 0.9307 - val_acc: 0.4269

Epoch 00009: val_acc did not improve from 0.43197
Epoch 10/80
75/75 [==============================] - 1s 17ms/step - loss: 0.9983 - acc: 0.4610 - val_loss: 0.9303 - val_acc: 0.4371

Epoch 00010: val_acc improved from 0.43197 to 0.43707, saving model to MC\Power\017390ck

75/75 [==============================] - 1s 13ms/step - loss: 0.9768 - acc: 0.5596 - val_loss: 0.9857 - val_acc: 0.5816

Epoch 00004: val_acc did not improve from 0.58163
Epoch 5/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9714 - acc: 0.5596 - val_loss: 0.9828 - val_acc: 0.5816

Epoch 00005: val_acc did not improve from 0.58163
Epoch 6/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9686 - acc: 0.5596 - val_loss: 0.9825 - val_acc: 0.5816

Epoch 00006: val_acc did not improve from 0.58163
Epoch 7/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9675 - acc: 0.5596 - val_loss: 0.9843 - val_acc: 0.5816

Epoch 00007: val_acc did not improve from 0.58163
Epoch 8/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9669 - acc: 0.5596 - val_loss: 0.9845 - val_acc: 0.5816

Epoch 00008: val_acc did not improve from 0.58163
Epoch 9/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9662 - acc: 0.5596 - val_l

75/75 [==============================] - 1s 11ms/step - loss: 0.8273 - acc: 0.5063 - val_loss: 0.8639 - val_acc: 0.5102

Epoch 00018: val_acc did not improve from 0.52551
Epoch 19/80
75/75 [==============================] - 1s 10ms/step - loss: 0.8271 - acc: 0.5050 - val_loss: 0.8663 - val_acc: 0.5068

Epoch 00019: val_acc did not improve from 0.52551
Epoch 1/80
75/75 [==============================] - 4s 22ms/step - loss: 1.0428 - acc: 0.4979 - val_loss: 0.7674 - val_acc: 0.7313

Epoch 00001: val_acc improved from -inf to 0.73129, saving model to MC\Finance\006800ckeckpointer.ckpt
Epoch 2/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0873 - acc: 0.5113 - val_loss: 0.8257 - val_acc: 0.7313

Epoch 00002: val_acc did not improve from 0.73129
Epoch 3/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9854 - acc: 0.5256 - val_loss: 0.8030 - val_acc: 0.7313

Epoch 00003: val_acc did not improve from 0.73129
Epoch 4/80
75/75 [=============================

75/75 [==============================] - 1s 10ms/step - loss: 1.0040 - acc: 0.4828 - val_loss: 1.0157 - val_acc: 0.4915

Epoch 00018: val_acc did not improve from 0.49660
Epoch 19/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0039 - acc: 0.4832 - val_loss: 1.0156 - val_acc: 0.4915

Epoch 00019: val_acc did not improve from 0.49660
Epoch 20/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0038 - acc: 0.4832 - val_loss: 1.0155 - val_acc: 0.4915

Epoch 00020: val_acc did not improve from 0.49660
Epoch 21/80
75/75 [==============================] - 1s 9ms/step - loss: 1.0037 - acc: 0.4832 - val_loss: 1.0154 - val_acc: 0.4915

Epoch 00021: val_acc did not improve from 0.49660
Epoch 22/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0036 - acc: 0.4828 - val_loss: 1.0153 - val_acc: 0.4915

Epoch 00022: val_acc did not improve from 0.49660
Epoch 23/80
75/75 [==============================] - 1s 9ms/step - loss: 1.0035 - acc: 0.4824 - va


Epoch 00019: val_acc did not improve from 0.88605
Epoch 20/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2798 - acc: 0.9244 - val_loss: 0.4048 - val_acc: 0.8861

Epoch 00020: val_acc did not improve from 0.88605
Epoch 21/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2798 - acc: 0.9244 - val_loss: 0.4051 - val_acc: 0.8861

Epoch 00021: val_acc did not improve from 0.88605
Epoch 22/80
75/75 [==============================] - 1s 11ms/step - loss: 0.2793 - acc: 0.9244 - val_loss: 0.4044 - val_acc: 0.8861

Epoch 00022: val_acc did not improve from 0.88605
Epoch 23/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2793 - acc: 0.9244 - val_loss: 0.4042 - val_acc: 0.8861

Epoch 00023: val_acc did not improve from 0.88605
Epoch 24/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2791 - acc: 0.9244 - val_loss: 0.4044 - val_acc: 0.8861

Epoch 00024: val_acc did not improve from 0.88605
Epoch 25/80
75/75 [===============

75/75 [==============================] - 1s 10ms/step - loss: 0.2745 - acc: 0.9244 - val_loss: 0.3980 - val_acc: 0.8861

Epoch 00064: val_acc did not improve from 0.88605
Epoch 65/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2744 - acc: 0.9244 - val_loss: 0.3979 - val_acc: 0.8861

Epoch 00065: val_acc did not improve from 0.88605
Epoch 66/80
75/75 [==============================] - 1s 11ms/step - loss: 0.2743 - acc: 0.9244 - val_loss: 0.3978 - val_acc: 0.8861

Epoch 00066: val_acc did not improve from 0.88605
Epoch 67/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2741 - acc: 0.9244 - val_loss: 0.3975 - val_acc: 0.8861

Epoch 00067: val_acc did not improve from 0.88605
Epoch 68/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2741 - acc: 0.9244 - val_loss: 0.3975 - val_acc: 0.8861

Epoch 00068: val_acc did not improve from 0.88605
Epoch 69/80
75/75 [==============================] - 1s 10ms/step - loss: 0.2739 - acc: 0.9244 - 


Epoch 00015: val_acc did not improve from 0.47109
Epoch 16/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9527 - acc: 0.4773 - val_loss: 0.9869 - val_acc: 0.4337

Epoch 00016: val_acc did not improve from 0.47109
Epoch 17/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9526 - acc: 0.4773 - val_loss: 0.9869 - val_acc: 0.4337

Epoch 00017: val_acc did not improve from 0.47109
Epoch 18/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9525 - acc: 0.4773 - val_loss: 0.9869 - val_acc: 0.4337

Epoch 00018: val_acc did not improve from 0.47109
Epoch 19/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9524 - acc: 0.4773 - val_loss: 0.9870 - val_acc: 0.4337

Epoch 00019: val_acc did not improve from 0.47109
Epoch 20/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9523 - acc: 0.4773 - val_loss: 0.9871 - val_acc: 0.4337

Epoch 00020: val_acc did not improve from 0.47109
Epoch 21/80
75/75 [===============

75/75 [==============================] - 1s 10ms/step - loss: 0.9538 - acc: 0.4652 - val_loss: 0.9628 - val_acc: 0.5102

Epoch 00032: val_acc did not improve from 0.51871
Epoch 33/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9538 - acc: 0.4652 - val_loss: 0.9627 - val_acc: 0.5102

Epoch 00033: val_acc did not improve from 0.51871
Epoch 34/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9537 - acc: 0.4643 - val_loss: 0.9626 - val_acc: 0.5102

Epoch 00034: val_acc did not improve from 0.51871
Epoch 35/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9537 - acc: 0.4656 - val_loss: 0.9625 - val_acc: 0.5102

Epoch 00035: val_acc did not improve from 0.51871
Epoch 36/80
75/75 [==============================] - 1s 10ms/step - loss: 0.9537 - acc: 0.4656 - val_loss: 0.9624 - val_acc: 0.5102

Epoch 00036: val_acc did not improve from 0.51871
Epoch 37/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9537 - acc: 0.4647 - 


Epoch 00001: val_acc improved from -inf to 0.27381, saving model to MC\Insurer\000060ckeckpointer.ckpt
Epoch 2/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0425 - acc: 0.5239 - val_loss: 1.1866 - val_acc: 0.2738

Epoch 00002: val_acc did not improve from 0.27381
Epoch 3/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0284 - acc: 0.5239 - val_loss: 1.1845 - val_acc: 0.2738

Epoch 00003: val_acc did not improve from 0.27381
Epoch 4/80
75/75 [==============================] - 1s 12ms/step - loss: 1.0254 - acc: 0.5239 - val_loss: 1.1836 - val_acc: 0.2738

Epoch 00004: val_acc did not improve from 0.27381
Epoch 5/80
75/75 [==============================] - 1s 11ms/step - loss: 1.0226 - acc: 0.5239 - val_loss: 1.1809 - val_acc: 0.2738

Epoch 00005: val_acc did not improve from 0.27381
Epoch 6/80
75/75 [==============================] - 1s 11ms/step - loss: 1.0208 - acc: 0.5239 - val_loss: 1.1771 - val_acc: 0.2738

Epoch 00006: val_acc did not improve

75/75 [==============================] - 1s 10ms/step - loss: 1.0860 - acc: 0.3468 - val_loss: 0.9599 - val_acc: 0.4337

Epoch 00002: val_acc did not improve from 0.46429
Epoch 3/80
75/75 [==============================] - 1s 11ms/step - loss: 1.0797 - acc: 0.3879 - val_loss: 0.9523 - val_acc: 0.4337

Epoch 00003: val_acc did not improve from 0.46429
Epoch 4/80
75/75 [==============================] - 1s 12ms/step - loss: 1.0767 - acc: 0.4013 - val_loss: 0.9512 - val_acc: 0.4337

Epoch 00004: val_acc did not improve from 0.46429
Epoch 5/80
75/75 [==============================] - 1s 12ms/step - loss: 1.0753 - acc: 0.4039 - val_loss: 0.9519 - val_acc: 0.4337

Epoch 00005: val_acc did not improve from 0.46429
Epoch 6/80
75/75 [==============================] - 1s 11ms/step - loss: 1.0750 - acc: 0.3992 - val_loss: 0.9525 - val_acc: 0.4337

Epoch 00006: val_acc did not improve from 0.46429
Epoch 7/80
75/75 [==============================] - 1s 10ms/step - loss: 1.0745 - acc: 0.4034 - val_l

75/75 [==============================] - 1s 14ms/step - loss: 0.8345 - acc: 0.4933 - val_loss: 0.8256 - val_acc: 0.5238

Epoch 00006: val_acc improved from 0.51871 to 0.52381, saving model to MC\Manufacturer\005380ckeckpointer.ckpt
Epoch 7/80
75/75 [==============================] - 1s 13ms/step - loss: 0.8342 - acc: 0.4958 - val_loss: 0.8247 - val_acc: 0.5238

Epoch 00007: val_acc did not improve from 0.52381
Epoch 8/80
75/75 [==============================] - 1s 19ms/step - loss: 0.8341 - acc: 0.4958 - val_loss: 0.8239 - val_acc: 0.5238

Epoch 00008: val_acc did not improve from 0.52381
Epoch 9/80
75/75 [==============================] - 1s 12ms/step - loss: 0.8339 - acc: 0.4941 - val_loss: 0.8233 - val_acc: 0.5238

Epoch 00009: val_acc did not improve from 0.52381
Epoch 10/80
75/75 [==============================] - 1s 12ms/step - loss: 0.8338 - acc: 0.4941 - val_loss: 0.8227 - val_acc: 0.5238

Epoch 00010: val_acc did not improve from 0.52381
Epoch 11/80
75/75 [====================


Epoch 00010: val_acc did not improve from 0.47619
Epoch 11/80
75/75 [==============================] - 1s 15ms/step - loss: 0.9963 - acc: 0.4517 - val_loss: 0.9148 - val_acc: 0.4762

Epoch 00011: val_acc did not improve from 0.47619
Epoch 12/80
75/75 [==============================] - 1s 14ms/step - loss: 0.9961 - acc: 0.4538 - val_loss: 0.9143 - val_acc: 0.4762

Epoch 00012: val_acc did not improve from 0.47619
Epoch 13/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9959 - acc: 0.4534 - val_loss: 0.9138 - val_acc: 0.4762

Epoch 00013: val_acc did not improve from 0.47619
Epoch 14/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9958 - acc: 0.4492 - val_loss: 0.9136 - val_acc: 0.4762

Epoch 00014: val_acc did not improve from 0.47619
Epoch 15/80
75/75 [==============================] - 1s 14ms/step - loss: 0.9956 - acc: 0.4513 - val_loss: 0.9130 - val_acc: 0.4762

Epoch 00015: val_acc did not improve from 0.47619
Epoch 16/80
75/75 [===============

75/75 [==============================] - 1s 13ms/step - loss: 0.9917 - acc: 0.4530 - val_loss: 0.9076 - val_acc: 0.4830

Epoch 00054: val_acc did not improve from 0.48299
Epoch 55/80
75/75 [==============================] - 1s 13ms/step - loss: 0.9916 - acc: 0.4526 - val_loss: 0.9074 - val_acc: 0.4830

Epoch 00055: val_acc did not improve from 0.48299
Epoch 56/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9915 - acc: 0.4526 - val_loss: 0.9072 - val_acc: 0.4847

Epoch 00056: val_acc improved from 0.48299 to 0.48469, saving model to MC\Manufacturer\000270ckeckpointer.ckpt
Epoch 57/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9914 - acc: 0.4534 - val_loss: 0.9070 - val_acc: 0.4881

Epoch 00057: val_acc improved from 0.48469 to 0.48810, saving model to MC\Manufacturer\000270ckeckpointer.ckpt
Epoch 58/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9913 - acc: 0.4530 - val_loss: 0.9070 - val_acc: 0.4847

Epoch 00058: val_acc did 

75/75 [==============================] - 1s 11ms/step - loss: 0.7861 - acc: 0.5390 - val_loss: 0.7930 - val_acc: 0.5476

Epoch 00014: val_acc did not improve from 0.54762
Epoch 15/80
75/75 [==============================] - 1s 13ms/step - loss: 0.7859 - acc: 0.5374 - val_loss: 0.7927 - val_acc: 0.5493

Epoch 00015: val_acc improved from 0.54762 to 0.54932, saving model to MC\Manufacturer\012330ckeckpointer.ckpt
Epoch 16/80
75/75 [==============================] - 1s 12ms/step - loss: 0.7858 - acc: 0.5378 - val_loss: 0.7925 - val_acc: 0.5493

Epoch 00016: val_acc did not improve from 0.54932
Epoch 17/80
75/75 [==============================] - 1s 13ms/step - loss: 0.7856 - acc: 0.5348 - val_loss: 0.7921 - val_acc: 0.5544

Epoch 00017: val_acc improved from 0.54932 to 0.55442, saving model to MC\Manufacturer\012330ckeckpointer.ckpt
Epoch 18/80
75/75 [==============================] - 1s 12ms/step - loss: 0.7853 - acc: 0.5369 - val_loss: 0.7918 - val_acc: 0.5493

Epoch 00018: val_acc did 

75/75 [==============================] - 1s 10ms/step - loss: 0.9738 - acc: 0.4500 - val_loss: 1.0616 - val_acc: 0.4286

Epoch 00002: val_acc improved from 0.40136 to 0.42857, saving model to MC\Manufacturer\033780ckeckpointer.ckpt
Epoch 3/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9730 - acc: 0.4337 - val_loss: 1.0639 - val_acc: 0.4286

Epoch 00003: val_acc did not improve from 0.42857
Epoch 4/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9715 - acc: 0.4622 - val_loss: 1.0639 - val_acc: 0.4286

Epoch 00004: val_acc did not improve from 0.42857
Epoch 5/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9707 - acc: 0.4584 - val_loss: 1.0627 - val_acc: 0.4286

Epoch 00005: val_acc did not improve from 0.42857
Epoch 6/80
75/75 [==============================] - 1s 11ms/step - loss: 0.9699 - acc: 0.4605 - val_loss: 1.0622 - val_acc: 0.4286

Epoch 00006: val_acc did not improve from 0.42857
Epoch 7/80
75/75 [======================

75/75 [==============================] - 1s 12ms/step - loss: 0.9083 - acc: 0.4639 - val_loss: 0.8538 - val_acc: 0.5255

Epoch 00002: val_acc improved from 0.50340 to 0.52551, saving model to MC\Manufacturer\009150ckeckpointer.ckpt
Epoch 3/80
75/75 [==============================] - 1s 14ms/step - loss: 0.9071 - acc: 0.4421 - val_loss: 0.8577 - val_acc: 0.4609

Epoch 00003: val_acc did not improve from 0.52551
Epoch 4/80
75/75 [==============================] - 1s 13ms/step - loss: 0.9056 - acc: 0.4538 - val_loss: 0.8591 - val_acc: 0.4456

Epoch 00004: val_acc did not improve from 0.52551
Epoch 5/80
75/75 [==============================] - 1s 13ms/step - loss: 0.9047 - acc: 0.4454 - val_loss: 0.8598 - val_acc: 0.4456

Epoch 00005: val_acc did not improve from 0.52551
Epoch 6/80
75/75 [==============================] - 1s 12ms/step - loss: 0.9042 - acc: 0.4505 - val_loss: 0.8602 - val_acc: 0.4456

Epoch 00006: val_acc did not improve from 0.52551
Epoch 7/80
75/75 [======================

In [42]:
with open('label_ratio_dic.pickle', 'rb') as f:
    label_ratio_dic = pickle.load(f)

In [48]:
certificated_stock_dic = {}
stock_acc_dic = {}
for sector_name, sector_model in model_dic.items():
    certificated_stock_dic[sector_name] = []
    stock_acc_dic[sector_name] = {}
    for stock_code, model in sector_model.items():
        s = model.evaluate(tf_dataset_test_dic[sector_name][stock_code])[1]
        stock_acc_dic[sector_name][stock_code] = s
        if s>0.55:
            print(f'{stock_code}: 의 레이블 비율')
            print(np.around(label_ratio_dic[sector_name][stock_code]*100,2))
            print(f'{stock_code} : 의 정확도 : {np.round(s*100,2)}')
            certificated_stock_dic[sector_name].append(stock_code)
        

19/19 [==============================] - 0s 9ms/step - loss: 0.7589 - acc: 0.5782
004370: 의 레이블 비율
상향    49.10
하향    47.89
횡보     3.01
Name: Label, dtype: float64
004370 : 의 정확도 : 57.82
19/19 [==============================] - 0s 8ms/step - loss: 0.6285 - acc: 0.8248
003410: 의 레이블 비율
횡보    87.83
하향     6.89
상향     5.28
Name: Label, dtype: float64
003410 : 의 정확도 : 82.48
19/19 [==============================] - 0s 8ms/step - loss: 0.7867 - acc: 0.5544
010130: 의 레이블 비율
하향    50.43
상향    47.83
횡보     1.74
Name: Label, dtype: float64
010130 : 의 정확도 : 55.44
19/19 [==============================] - 0s 8ms/step - loss: 0.7819 - acc: 0.7126
047040: 의 레이블 비율
횡보    64.18
상향    18.60
하향    17.22
Name: Label, dtype: float64
047040 : 의 정확도 : 71.26
19/19 [==============================] - 0s 8ms/step - loss: 0.9433 - acc: 0.6531
028670: 의 레이블 비율
횡보    54.62
상향    24.88
하향    20.50
Name: Label, dtype: float64
028670 : 의 정확도 : 65.31
12/12 [==============================] - 0s 11ms/step - loss: 0.8733 -

In [49]:
with open('certificated_stock_dic.pickle', 'wb') as f:
    pickle.dump(certificated_stock_dic,f)
with open('stock_acc_dic.pickle', 'wb') as f:
    pickle.dump(stock_acc_dic,f)